config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      post '/likes', to: 'likes#create', as: :likes
    end
  end
end

app/models/application_record.rb
# Base class for all ActiveRecord models in the application.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# Represents a comment associated with a post and a user.
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
# Represents a like associated with a post and a user.
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counters: post.likes.count)
  end
end

app/models/post.rb
# Represents a post belonging to an author.
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counters, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_initialize do |post|
    post.comments_counter ||= 0
    post.likes_counters ||= 0
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_posts_counter

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_initialize do |user|
    user.posts_counter ||= 0
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def new
    @post = Post.find(params[:post_id])
    @user = @post.author
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params.merge(post: @post))
    @comment.author = current_user

    if @comment.save
      flash[:success] = 'Comment successfully added! 😎'
      redirect_to user_post_path(@post.author, @post)
    else
      flash[:alert] = 'Comment not added! 😢'
      puts flash[:alert]
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])

    if @post.author
      @like = current_user.likes.build(post: @post)

      if @like.save
        flash[:success] = 'Like successfully added 😎!'
      else
        flash[:alert] = 'Could not add a like 😢!'
      end

      redirect_to user_post_path(@post.author, @post)
    else
      flash[:alert] = 'Post author not found 😢!'
      redirect_to root_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created successfully😎!'
      redirect_to user_posts_path(current_user)
    else
      flash[:alert] = 'Post not created😢!'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="container">
  <div class="form_container">
    <h2 class="">Create a new comment</h2>
    <%= form_with(model: [@user, @post, Comment.new], url: user_post_comments_path(@user, @post), local: true) do |f| %>
      <%= f.hidden_field :user_id, value: @post.author.id %>
      <div class="form_group">
        <%= f.label :text %>
        <%= f.text_area :text, class: 'form_control' %>
      </div>
      <div class="form_group">
        <%= f.submit "Save comment", class: "btn btn-outline-secondary rounded-pill m-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="nav-bar">
      <ul>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [user, post], local: true, url: user_posts_path(user)) do |f| %>
  <div class="form_group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form_control' %>
  </div>
  <div class="form_group">
    <%= f.label :text %>
    <%= f.text_area :text, class: 'form_control' %>
  </div>
  <%= f.submit "Save post", class: 'btn' %>
<% end %>

app/views/posts/index.html.erb
<h1>This is a list of all Posts written by <%= @user.name %></h1>

<div class="d-flex align-items-center mb-3 gap-3">
  <img src="<%= @user.photo%>" alt="user_image" class="border p-5 border-5" />
  <div class="border border-5 w-100 p-3">
    <h2><%= @user.name %></h2>
    <div class="d-flex justify-content-end">
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
</div>

<section>
  <% @posts.each do |post| %>
    <a href="<%= "/users/#{ @user.id }/posts/#{ post.id }" %>" class="text-decoration-none text-primary-emphasis">
      <div class="border border-5 gap-3">
        <h3>Post #<%= post.id %></h3>
        <p><%= post.text %></p>

        <div class="d-flex justify-content-end">
          <span>Comments: <%= "#{ post.comments_counter || 0 }"%></span>
          <span>, Likes: <%= "#{ post.likes_counters || 0 }"%></span>
        </div>
      </div>
    </a>

    <div class="border border-5 mt-3 mb-3">
      <h4 class="mb-3">Comments</h4>
      <% post.recent_comments.each do |comment| %>
        <div class="mb-3">
          <span><%= comment.author.name %>:</span>
          <span> <%= comment.text %></span>
        </div>  
      <% end %>
    </div>
  <% end %>
</section>

<div class="text-center p-4">
  <%= link_to "Create new post", new_user_post_path(@user), class: "btn btn-outline-secondary rounded-pill m-2 text-decoration-none" %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="form_container">
    <h2 class="">Create a new post</h2>
    
    <%= render partial: 'form', locals: { user: @user, post: @post } %>
    
  </div>
</div>

app/views/posts/show.html.erb
<section>
  <div class="border border-5 p-1 mb-3">
    <div class="d-flex justify-content-between align-items-center">
      <h2>
        <%= @post.title %> #<%= @post.id %> by <%= @user.name %>
      </h2>
      <div>
        <span>Comments: <%= @post.comments_counter %></span>
        <span>, Likes: <%= @post.likes_counters %></span>
       <%= button_to "Like", user_post_likes_path(@user, @post), method: :post %>
      </div>
    </div>
    <div>
      <%= @post.text %>
    </div>
  </div>

  <div class="border border-5 p-1 mb-3">
  <% @post.recent_comments.each do |comment| %>
      <div class="mt-3">
        <span><%= comment.author.name %>:</span>
        <span><%= comment.text %></span>
      </div>
    <% end %>
  </div>
  <div class="text-center p-4">
    <%= link_to 'Create a Comment', new_user_post_comment_path(@post.author, @post), class: 'btn' %>
  </div>
</section>

app/views/users/index.html.erb
<h1 class="text-center mb-3">Here are all our unique Users😎</h1>
<section  class="w-100">
  <% @users.each do |user| %>
    <a href="/users/<%= user.id%>" class="d-flex align-items-center mb-3 gap-3 text-decoration-none">
      <img src="<%= user.photo %>" class="border p-5 border-5" />
      <div class="border border-5 w-100  p-3">
        <h2 class="flex-grow-1"><%= user.name %></h2>
        <div class="d-flex justify-content-end">
          Number of post:
          <%= user.posts_counter %>
        </div>
      </div>
    </a>
  <% end %>
</section>

app/views/users/show.html.erb
<h1>These are the details of our unique user, <%= @user.name %></h1>

<section class="d-flex align-items-center mb-3 gap-3">
  <div> 
    <%= image_tag(@user.photo, class: "border p-5 border-5") %>
  </div>
  <div class="border border-5 w-100 p-3">
    <h2><%= @user.name %></h2>
    <div class="d-flex justify-content-end">
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
</section>

<div class="border border-5 mx-auto w-100 p-3 mb-3">
  <h2>Bio</h2>
  <p><%= @user.bio %></p>
</div>

<div>
  <% @user.recent_posts.each do |post| %>
    <div class="border border-5 mx-auto w-100 p-3 mb-3">
      <%= link_to user_post_path(@user, post) do %>
        <h2>
          <%= post.title %>#
          <%= post.id %>
        </h2>
      <% end %>
      <p><%= post.text %></p>
      <div class="d-flex justify-content-end">
        <span>Comments: <%= "#{post.comments_counter || 0}" %></span>
        <span>, Likes: <%= "#{post.likes_counters || 0}" %></span>
      </div>
    </div>
  <% end %>
</div>

<div class="text-center p-4">
  <a href=<%= "/users/#{ @user.id }/posts" %>>
    <button type="button" clarailsss="btn btn-primary rounded-pill">
      See All Posts
    </button>
  </a>
</div>